# Generated by Django 5.2.7 on 2025-10-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia_id', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('gerente', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('dtanascimento', models.DateField()),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('dtacadastro', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.IntegerField(unique=True)),
                ('agencia', models.IntegerField()),
                ('cpf', models.IntegerField(unique=True)),
                ('tipo', models.IntegerField(choices=[(1, 'Corrente'), (2, 'Poupança'), (3, 'Salário')])),
                ('saldo', models.FloatField()),
                ('dtaabertura', models.DateField()),
                ('status', models.BooleanField()),
                ('limite_diario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_conta', models.IntegerField()),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField()),
                ('tipo', models.IntegerField(choices=[(1, 'Dinheiro'), (2, 'Cheque'), (3, 'Transferência'), (4, 'PIX')])),
                ('descricao', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Saque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_conta', models.IntegerField()),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField()),
                ('local', models.IntegerField(choices=[(1, 'Caixa'), (2, 'Caixa Eletrônico')])),
                ('descricao', models.CharField(max_length=255)),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('status_operacao', models.IntegerField(choices=[(1, 'Aprovado'), (2, 'Negado')])),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_origem', models.IntegerField()),
                ('nro_destino', models.IntegerField()),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField()),
                ('tipo', models.IntegerField(choices=[(1, 'TED'), (2, 'DOC'), (3, 'PIX'), (4, 'Transferencia Interna')])),
                ('descricao', models.CharField(max_length=255)),
                ('status_operacao', models.IntegerField(choices=[(1, 'Aprovado'), (2, 'Negado')])),
            ],
        ),
    ]
